### ISSUE TITLE
Missing modules babel-runtime, aws ?

### ISSUE THREAD

**Issue by t3rminus** [Upplication/gulp-elasticbeanstalk-deploy#3]
Seems a module that is listed as a devDependancy might be required to run? Or is there a build script that needs to be run?

I installed with `npm install --save-dev gulp-elasticbeanstalk-deploy`

```
Error: Cannot find module 'babel-runtime/core-js/object/assign'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (node_modules/gulp-elasticbeanstalk-deploy/lib/index.js:8:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by t3rminus** [comment]
Or maybe I'm missing something else entirely?

```
Error: Cannot find module './aws'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node_modules/gulp-elasticbeanstalk-deploy/lib/index.js:173:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by Souler** [comment]
Nothing on your side, probably a mistake by my side while recently rewriting the project to ES6 with babel.
I'm looking on it right no :)

**Comment by Souler** [comment]
Ok, should be fixed on version **1.0.2**. It was both, a problem with a missing dependency and a problem with `.npmignore` and npm publishing. Could you please close the issue after testing it actually works?

Also, big thanks to @saby-echo for pointing also another underlaying bug that should be fixed by now.

And finally, sorry for the incovenience, as I said earlier this project went through a major overhaul and somethings still buggy/broken :(

**Comment by t3rminus** [comment]
Well, it's not complaining about missing requirements anymore, but `require('gulp-elasticbeanstalk-deploy')` does not return a function per your docs. It returns an es6 module. `require('gulp-elasticbeanstalk-deploy').default` seems to return the correct function.

**Comment by Souler** [comment]
mmm, theorically the `add-module-exports` plugin should take care of that, i'll look into it tomorrow

**Comment by Souler** [comment]
Ok, so the problem was i didn't read the docs for the plugin enough to actually make it work. `require('gulp-elasticbeanstalk-deploy')` should be working now.
Thanks again for pointing out the problem :)

**Comment by t3rminus** [comment]
No problem. It definitely seems to be working for me now. Thanks!
